import type { Metadata } from "next";
import { Inter, Rubik, Work_Sans } from "next/font/google";

import "@/styles/globals.css";

import { Header } from "@/components/header";
import { cn } from "@/utils/cn";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const sans = Work_Sans({ subsets: ["latin"], variable: "--font-sans" });
const rubik = Rubik({ subsets: ["latin"], variable: "--font-rubik" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout(props: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.variable,
          sans.variable,
          rubik.variable,
          "flex min-h-screen flex-col overscroll-none bg-background font-sans text-blue-gray-900 antialiased",
        )}
      >
        <Header />
        {props.children}
      </body>
    </html>
  );
}
